### ISSUE TITLE
Bricked boot screen no control 

### ISSUE THREAD

**Issue by M-CHAMP** [houseofbugs/TH3D-Unified-U1.R2#1]
Anet a8 v1.0 board 
Update was unaware they removed the control menu guess it would help if read the update.... 
Under the sub menus of control, only temperature shows any items all others are empty... 

Boot screen is bricked... Not sure if im missing a library or what cannot figure it out

**Comment by houseofbugs** [comment]
The missing menu items is normal. Please read the FAQ located at http://Firmware.Th3DStudio.com

As for the bootscreen it will not display on certain machine configs due to space limitations.
