### ISSUE TITLE
Ender 3 issues with latest U1.R2.9b

### ISSUE THREAD

**Issue by Rian-Striegel** [houseofbugs/TH3D-Unified-U1.R2#11]
Sketch to large if Ender 3 with probe and linear advance selected:

Sketch uses 130194 bytes (100%) of program storage space. Maximum is 130048 bytes.
Global variables use 5207 bytes (31%) of dynamic memory, leaving 11177 bytes for local variables. Maximum is 16384 bytes.

**Comment by Rian-Striegel** [comment]
Solved by adding
#define NO_COLD_PREVENT
in the Ender 3 section

I can live without the cold extrusion prevention...

**Comment by houseofbugs** [comment]
Try the latest FW (9c) on here. Make sure you are using Arduino 1.8.7 as well. Compiled sizes can vary based on the IDE used.

**Comment by houseofbugs** [comment]
Give this one a try: https://github.com/houseofbugs/TH3D-Unified-U1.R2/releases/tag/U1.R2.9c-BETA
