### ISSUE TITLE
Wanhao "i3 INVERT_Y_DIR" value incorrect for v2.1 Duplicator i3

### ISSUE THREAD

**Issue by alxpx** [houseofbugs/TH3D-Unified-U1.R2#13]
Thanks for all your hard work on the Unified Firmware and EZABL!

While setting up the Unified Firmware on my Monoprice-skinned v2.1 Wanhao Duplicator i3, I found that it was necessary to change Line 941 from:

"  #define INVERT_Y_DIR false"

to

"  #define INVERT_Y_DIR true" 

in Configuration_backend.h to have the bed move in the proper direction (Y 0 at the rear of the machine).

To the best of my knowledge, Y 0 is at the rear on all Wanhao Di3 versions, but as I only have experience with the above model, I can't verify if this is the same with v2.0 and earlier.  At time of testing, all hardware and wiring on my machine was stock.

Best Wishes,

AlxPx

**Comment by houseofbugs** [comment]
We have a monoprice V2.1 here and did not have that issue. Maybe you had a one off that was belted or the stepper was wired wrong? This is the first report of this kind of issue.

**Comment by houseofbugs** [comment]
If you can please confirm the last reply I would love to see what machine you have. Just reply to re-open.
