### ISSUE TITLE
TH3D_UFW_U1.R2.10d crashes

### ISSUE THREAD

**Issue by Xeliaa** [houseofbugs/TH3D-Unified-U1.R2#14]
This version will randomly crash the printer and stay in a blue screen when its heated up bed/hotend especially when connected to a computer and had commands issued from the program and then use the radial knob to do things like move axis. its reproducable for me by going in using pronterface and heating the bed/hotend and sending a M502 waiting and then attempt to go thru steps of calibrating EZABL
and when trying to connect to it while its bluescreen it will begin beeping and jerking the axis motors

======================================================
Attempted to write invalid text to console, which could be due to an invalid baudrate
start
echo:Marlin TH3D U1.R2.10d
echo: Last Updated:  | Author: (TH3D)
echo:Compiled: Apr 18 2019
echo: Free Memory: 11348  PlannerBufferBytes: 1488
echo:V55 stored settings retrieved (start
echo:Marlin TH3D U1.R2.10d
echo: Last Updated:  | Author: (TH3D)
echo:Compiled: Apr 18 2019
echo: Free Memory: 11348  PlannerBufferBytes: 1488
echo:V55 stored settings retrieved (¾¾¾¾¾¾¾¾¾¾¾¾¾¾¾¾start
echo:Marlin TH3D U1.R2.10d
echo: Last Updated:  | Author: (TH3D)
echo:Compiled: Apr 18 2019
echo: Free Memory: 11348  PlannerBufferBytes: 1488
×#<·Ñ8wÌ+2••æ$±O
Attempted to write invalid text to console, which could be due to an invalid baudrate
start
echo:Marlin TH3D U1.R2.10d
echo: Last Updated:  | Author: (TH3D)
echo:Compiled: Apr 18 2019
echo: Free Memory: 11348  PlannerBufferBytes: 1488
echo:V55 stored settings retrieved (start
echo:Marlin TH3D U1.R2.10d
echo: Last Updated:  | Author: (TH3D)
echo:Compiled: Apr 18 2019
echo: Free Memory: 11348  PlannerBufferBytes: 1488
echo:V55 stored settings retrieved (‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚‚start
echo:Marlin TH3D U1.R2.10d
echo: Last Updated:  | Author: (TH3D)
echo:Compiled: Apr 18 2019
echo: Free Memory: 11348  PlannerBufferBytes: 1488
×#<·Ñ8wÌ+2••æ$±O
Attempted to write invalid text to console, which could be due to an invalid baudrate
===============================================

This is on a Ender 5 Stock with EZABL

**Comment by houseofbugs** [comment]
We don't handle tech support on GitHub. Please contact Support@TH3DStudio.com and include your order number.

I did try this on our Ender 5 and was not able to reproduce the issue.
