### ISSUE TITLE
Ezabl heavy duty mount offset wrong side

### ISSUE THREAD

**Issue by Liger0** [houseofbugs/TH3D-Unified-U1.R2#16]
The preset heavy duty mount ezabl offset is a positive value, probably around +41.
The heavy duty ABL mount is on the left side though, and it has an offset value of -41.5, so a negative (integer, as the firmware requires) number like -41 should be used.

**Comment by houseofbugs** [comment]
Read the manual. This is correct for the right side which is what ships with the firmware pack. Use a custom mount.
