### ISSUE TITLE
BLTouch issue

### ISSUE THREAD

**Issue by InvalidExcepti0n** [houseofbugs/TH3D-Unified-U1.R2#2]
Hi

Enabling BLTouch in configuration can't compile at all (if comment it works fine)
Getting error:

`In file included from sketch/MarlinConfig.h:42:0,
                 from sketch/G26_Mesh_Validation_Tool.cpp:27:
SanityCheck.h:791: error: #error "Please enable only one probe option: PROBE_MANUALLY, FIX_MOUNTED_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
   #error "Please enable only one probe option: PROBE_MANUALLY, FIX_MOUNTED_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
    ^
exit status 1
#error "Please enable only one probe option: PROBE_MANUALLY, FIX_MOUNTED_PROBE, BLTOUCH, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."`

Any solution for this???

**Comment by BiasF** [comment]
same problem here

**Comment by BTopbas** [comment]
same here. Th3d old verisons no problem and i can use bltouch. But u1.r2 versions i cant add.
