### ISSUE TITLE
Git (release) tag for U1.R2.7

### ISSUE THREAD

**Issue by fspijkerman** [houseofbugs/TH3D-Unified-U1.R2#4]
Hello!

Thanks for making your custom changes available!

Is it possible to create git tags for each version, like a release tag for U1.R2.7 (4da6c63191fcc6cc794bb39af0f6bba2620c5b76). 
I've forked your repository to keep track of my custom changes, a git version tag will make it easier to maintain and keep it up to date.

Best regards,
Frank

**Comment by houseofbugs** [comment]
This github is so we can internally track changes for releases. We don't direct people to here to download. We don't use the release feature on here. We do email and post on our site, social media accounts when a new release is ready.
