### ISSUE TITLE
Ender 5 Issue

### ISSUE THREAD

**Issue by derbe89** [houseofbugs/TH3D-Unified-U1.R2#6]
When compiling for stock Ender 5 I'm getting the error:

```
exit status 1
#error "Enable USE_XMAX_PLUG when homing X to MAX."
```

Nothing was altered, just uncommented "#define ENDER5" in configuration.h

**Comment by VanceK** [comment]
I did the same thing and getting the same error.

**Comment by houseofbugs** [comment]
Per the release notes posted this Github is for testing only. The Ender 5 is supported now but you should always download from http://firmware.th3dstudio.com.
